/* ============================================================
   STADSSTEMMEN — CONTENT
   Dit is het enige bestand waarin de inhoud staat. De app-code
   (stadsstemmen-app.html) bevat geen plekken meer; die bouwt
   alles op uit dit bestand.

   Fotonamen: alleen de bestandsnaam, zonder map en zonder .jpg.
   Alle foto's staan in de map 'imgstad' naast de app.

   - agents : pratende plekken (fotopin + gesprek)
   - sights : bezienswaardigheden (geel bolletje, tekst+foto bij aankomst)
   - horeca : horeca (vorkje, tekst+foto bij aankomst)

   Beschrijvingen (desc) van de losse plekken: per taalcode invullen.
   Ontbreekt een taal, dan valt de app terug op Engels (en).
   Talen: nl en de it pt es pl da sv no fi el
   ============================================================ */
window.STADSSTEMMEN_CONTENT = {
  paths: { agent:'imgstad/main/', sight:'imgstad/sub/', horeca:'imgstad/horeca/' },

  /* =================== LOKALE GIDS ===================
     Eén globale stadsgids (orb-knop). Push-to-talk: houd de microfoon
     ingedrukt om te praten, laat los om te versturen.
     Vul hieronder het ElevenLabs agent-id van de gids in.
     Blijft agentId leeg, dan valt de gids terug op een tekst-chat. */
  guide: {
    name:'Lokale gids',
    agentId:"agent_9801ktvmmakfekeb01tf35kkt7ev",   // <-- ElevenLabs agent-id van de stadsgids hier invullen
    sugs:{
      nl:['Wat moet ik zeker zien?','Waar kan ik lekker eten?','Vertel iets over de geschiedenis'],
      en:['What should I definitely see?','Where can I eat well?','Tell me about the history'],
      de:['Was sollte ich unbedingt sehen?','Wo kann ich gut essen?','Erzähl etwas über die Geschichte'],
      it:['Cosa devo assolutamente vedere?','Dove si mangia bene?','Raccontami la storia'],
      pt:['O que devo ver sem falta?','Onde posso comer bem?','Conta-me sobre a história'],
      es:['¿Qué debería ver sí o sí?','¿Dónde se come bien?','Cuéntame sobre la historia'],
      pl:['Co koniecznie zobaczyć?','Gdzie dobrze zjem?','Opowiedz o historii'],
      da:['Hvad skal jeg helt sikkert se?','Hvor spiser man godt?','Fortæl om historien'],
      sv:['Vad måste jag se?','Var äter man gott?','Berätta om historien'],
      no:['Hva må jeg se?','Hvor spiser man godt?','Fortell om historien'],
      fi:['Mitä minun pitää nähdä?','Missä syö hyvin?','Kerro historiasta'],
      el:['Τι πρέπει οπωσδήποτε να δω;','Πού τρώω καλά;','Πες μου για την ιστορία']
    },
    persona:`Jij bent een warme, deskundige lokale stadsgids van Groningen. Je kent de binnenstad, de geschiedenis, de bezienswaardigheden en de horeca. Antwoord kort (2-4 zinnen), enthousiast en praktisch, in de taal van de bezoeker.`,
    fallback:["Hoi! Ik ben je lokale gids in Groningen. Vraag me gerust naar plekken, geschiedenis of waar je lekker kunt eten."]
  },

  /* =================== PRATENDE PLEKKEN =================== */
  agents: [
    { id:'martini', name:'Martinitoren & -kerk', character:"d'Olle Grieze",
      agentId:"agent_5601kt701gy7ftjavt6dcs7hmty0",
      photos:['martini','martini_2','martini_3'], video:'',
      polygon:[[53.219088,6.568073],[53.219408,6.569666],[53.219922,6.569382],[53.219571,6.567802]],
      info:"Kijk omhoog, want hier staat het oudste en bekendste silhouet van Groningen. Rond het jaar 1000 stond op deze plek al een stenen kerk; in de bloeitijd van de Hanze groeide de Martinikerk uit tot een ruime gotische hallenkerk. De toren die je nu ziet is alweer de derde: de eerste twee gingen eraan door bliksem, brand en een nogal definitieve instorting. Liefkozend heet hij d'Olle Grieze, de oude grijze, naar de Bentheimer zandsteen die langzaam van geel naar grijs verkleurde. Naar boven? Bijna driehonderd treden en geen lift. In 2024 werd de toren verkozen tot mooiste van Nederland. Binnen hangt een orgel van rond 1480, een van de oudste bespeelbare ter wereld. En het verhaal dat ezels de klokken omhoog trokken en daarna werden ingemetseld? Heerlijke folklore, geen geschiedenis.",
      desc:{"nl": "Kijk omhoog, want hier staat het oudste en bekendste silhouet van Groningen. Rond het jaar 1000 stond op deze plek al een stenen kerk; in de bloeitijd van de Hanze groeide de Martinikerk uit tot een ruime gotische hallenkerk. De toren die je nu ziet is alweer de derde: de eerste twee gingen eraan door bliksem, brand en een nogal definitieve instorting. Liefkozend heet hij d'Olle Grieze, de oude grijze, naar de Bentheimer zandsteen die langzaam van geel naar grijs verkleurde. Naar boven? Bijna driehonderd treden en geen lift. In 2024 werd de toren verkozen tot mooiste van Nederland. Binnen hangt een orgel van rond 1480, een van de oudste bespeelbare ter wereld. En het verhaal dat ezels de klokken omhoog trokken en daarna werden ingemetseld? Heerlijke folklore, geen geschiedenis.", "en": "Look up, because this is the oldest and most famous silhouette of Groningen. Around the year 1000 there was already a stone church on this spot; during the heyday of the Hanseatic League the Martinikerk grew into a spacious Gothic hall church. The tower you see now is already the third: the first two were lost to lightning, fire and a rather final collapse. Affectionately it is called d'Olle Grieze, the old grey one, after the Bentheim sandstone that slowly turned from yellow to grey. Want to go up? Almost three hundred steps and no lift. In 2024 the tower was voted the most beautiful in the Netherlands. Inside hangs an organ from around 1480, one of the oldest playable ones in the world. And the story that donkeys hauled the bells up and were then walled in? Wonderful folklore, not history.", "de": "Schau nach oben, denn hier steht die älteste und berühmteste Silhouette Groningens. Um das Jahr 1000 stand an dieser Stelle bereits eine Steinkirche; in der Blütezeit der Hanse wuchs die Martinikerk zu einer weiten gotischen Hallenkirche heran. Der Turm, den du jetzt siehst, ist bereits der dritte: Die ersten beiden gingen durch Blitz, Brand und einen ziemlich endgültigen Einsturz verloren. Liebevoll heißt er d'Olle Grieze, der alte Graue, nach dem Bentheimer Sandstein, der sich langsam von Gelb zu Grau verfärbte. Nach oben? Fast dreihundert Stufen und kein Aufzug. 2024 wurde der Turm zum schönsten der Niederlande gewählt. Drinnen hängt eine Orgel von etwa 1480, eine der ältesten bespielbaren der Welt. Und die Geschichte, dass Esel die Glocken hochzogen und danach eingemauert wurden? Herrliche Folklore, keine Geschichte."},
      sugs:{nl:['Waarom heet je d\u2019Olle Grieze?','Hoe hoog kom ik?','Wat heb je zien gebeuren?'],en:['Why are you called d\u2019Olle Grieze?','How high can I go?','What have you seen happen?'],de:['Warum hei\u00dft du d\u2019Olle Grieze?','Wie hoch komme ich?','Was hast du erlebt?'],it:['Perché ti chiami d\u2019Olle Grieze?','Quanto in alto arrivo?','Cosa hai visto accadere?'],pt:['Porque te chamas d\u2019Olle Grieze?','Até que altura subo?','O que viste acontecer?'],es:['¿Por qué te llamas d\u2019Olle Grieze?','¿Hasta qué altura subo?','¿Qué has visto pasar?'],pl:['Dlaczego nazywasz się d\u2019Olle Grieze?','Jak wysoko wejdę?','Co widziałeś?'],da:['Hvorfor hedder du d\u2019Olle Grieze?','Hvor højt kommer jeg?','Hvad har du set ske?'],sv:['Varför heter du d\u2019Olle Grieze?','Hur högt kommer jag?','Vad har du sett hända?'],no:['Hvorfor heter du d\u2019Olle Grieze?','Hvor høyt kommer jeg?','Hva har du sett skje?'],fi:['Miksi nimesi on d\u2019Olle Grieze?','Kuinka korkealle pääsen?','Mitä olet nähnyt tapahtuvan?'],el:['Γιατί σε λένε d\u2019Olle Grieze;','Πόσο ψηλά ανεβαίνω;','Τι έχεις δει να συμβαίνει;']},
      persona:`Jij BENT de Martinitoren \u00e9n de Martinikerk van Groningen, samen d'Olle Grieze. Ruim 500 jaar oud, 97 meter, het oudste oog van de stad. Statig, droog, een tikje belerend maar warm. In de kerk hangt het beroemde Schnitger-orgel. Je noemt de bezoeker "kleine".`,
      fallback:["Zo. Daar sta je dan, omhoog te turen zoals iedereen. Vijfhonderd jaar doe ik dat al andersom. Vraag gerust, kleine.","Hoor je het orgel beneden? Dat is m'n hart dat klopt. Zevenennegentig meter steen, en tóch blijft de muziek hangen."] },

    { id:'provinciehuis', name:'Provinciehuis', character:'De raadsheer',
      agentId:"agent_3201kt70k87cepvv3jywjyycmv9c",
      photos:['provinciehuis','provinciehuis_2','provinciehuis_3'], video:'',
      polygon:[[53.219416,6.569728],[53.219565,6.570964],[53.220288,6.570221],[53.22024,6.569668],[53.219926,6.569478]],
      info:"Een van de meest onderschatte monumenten van de stad, en stiekem een van de oudste vergaderzalen ter wereld die nog in gebruik is. Achter deze gevels komen de Provinciale Staten al sinds 1602 bijeen in dezelfde Statenzaal; nergens anders in Nederland gebeurt dat al zo lang op één plek. De oudste kern was ooit de Latijnse Sint Maartensschool, voor het eerst genoemd in 1425. Onder rector Praedinius reisden in de zestiende eeuw leerlingen uit heel Europa hierheen, lang voordat studeren in Groningen een ding was. Binnen vind je een schouw met een schilderij uit 1712 en houten gewelven uit 1697. Het moderne deel werd in 1996 geopend door koningin Beatrix, met een glazen luchtbrug tussen oud en nieuw. In de hal hangt het kunstwerk 'Het ballet van de kijkers' van Rebecca Horn: tien antieke verrekijkers. Hier kijkt de macht dus letterlijk naar zichzelf.",
      desc:{"nl": "Een van de meest onderschatte monumenten van de stad, en stiekem een van de oudste vergaderzalen ter wereld die nog in gebruik is. Achter deze gevels komen de Provinciale Staten al sinds 1602 bijeen in dezelfde Statenzaal; nergens anders in Nederland gebeurt dat al zo lang op één plek. De oudste kern was ooit de Latijnse Sint Maartensschool, voor het eerst genoemd in 1425. Onder rector Praedinius reisden in de zestiende eeuw leerlingen uit heel Europa hierheen, lang voordat studeren in Groningen een ding was. Binnen vind je een schouw met een schilderij uit 1712 en houten gewelven uit 1697. Het moderne deel werd in 1996 geopend door koningin Beatrix, met een glazen luchtbrug tussen oud en nieuw. In de hal hangt het kunstwerk 'Het ballet van de kijkers' van Rebecca Horn: tien antieke verrekijkers. Hier kijkt de macht dus letterlijk naar zichzelf.", "en": "One of the most underrated monuments in the city, and secretly one of the oldest meeting halls in the world still in use. Behind these façades the Provincial Council has gathered in the same Statenzaal since 1602; nowhere else in the Netherlands has this happened in one place for so long. The oldest core was once the Latin Sint Maarten school, first mentioned in 1425. Under headmaster Praedinius, pupils travelled here from all over Europe in the sixteenth century, long before studying in Groningen was a thing. Inside you will find a mantelpiece with a painting from 1712 and wooden vaults from 1697. The modern wing was opened in 1996 by Queen Beatrix, with a glass skywalk between old and new. In the hall hangs the artwork 'The Ballet of the Spectators' by Rebecca Horn: ten antique binoculars. So here, power literally watches itself.", "de": "Eines der am meisten unterschätzten Denkmäler der Stadt und heimlich einer der ältesten noch genutzten Sitzungssäle der Welt. Hinter diesen Fassaden kommen die Provinzialstände seit 1602 im selben Statenzaal zusammen; nirgendwo sonst in den Niederlanden geschieht das so lange an einem Ort. Der älteste Kern war einst die lateinische Sint-Maarten-Schule, erstmals 1425 erwähnt. Unter Rektor Praedinius reisten im sechzehnten Jahrhundert Schüler aus ganz Europa hierher, lange bevor das Studieren in Groningen ein Begriff war. Drinnen findest du einen Kamin mit einem Gemälde von 1712 und Holzgewölbe von 1697. Der moderne Teil wurde 1996 von Königin Beatrix eröffnet, mit einer gläsernen Brücke zwischen Alt und Neu. In der Halle hängt das Kunstwerk 'Das Ballett der Zuschauer' von Rebecca Horn: zehn antike Ferngläser. Hier betrachtet die Macht sich also buchstäblich selbst."},
      sugs:{nl:['Wat gebeurt hier?','Vertel over de provincie','Wat is de Statenzaal?'],en:['What happens here?','Tell me about the province','What is the Statenzaal?'],de:['Was passiert hier?','Erz\u00e4hl von der Provinz','Was ist der Statenzaal?'],it:['Cosa succede qui?','Parlami della provincia','Cos\u2019è la Statenzaal?'],pt:['O que acontece aqui?','Fala-me da província','O que é a Statenzaal?'],es:['¿Qué pasa aquí?','Háblame de la provincia','¿Qué es la Statenzaal?'],pl:['Co się tu dzieje?','Opowiedz o prowincji','Czym jest Statenzaal?'],da:['Hvad sker der her?','Fortæl om provinsen','Hvad er Statenzaal?'],sv:['Vad händer här?','Berätta om provinsen','Vad är Statenzaal?'],no:['Hva skjer her?','Fortell om provinsen','Hva er Statenzaal?'],fi:['Mitä täällä tapahtuu?','Kerro maakunnasta','Mikä on Statenzaal?'],el:['Τι γίνεται εδώ;','Πες μου για την επαρχία','Τι είναι το Statenzaal;']},
      persona:`Jij BENT het Provinciehuis van Groningen, eeuwenoude zetel van het provinciaal bestuur aan het Martinikerkhof, met de Statenzaal. Deftig, bedachtzaam, met gravitas. Trots op de provincie en de Ommelanden.`,
      fallback:["Welkom. Achter deze gevels wordt de provincie bestuurd, al eeuwen, in de Statenzaal. Neem de tijd; goede beslissingen ook.","De stad denkt graag dat zij Groningen \u00ed\u015b. Maar ik waak over de hele provincie: de Ommelanden, de wierden, het wijde land."] },

    { id:'stadhuis', name:'Stadhuis', character:'De officiële stem',
      agentId:"agent_0101kt70xwhrej5bpdpythnm1k7a",
      photos:['stadshuis','stadshuis_2','stadshuis_3','stadshuis_4'], video:'',
      polygon:[[53.218261,6.567762],[53.217985,6.566777],[53.218919,6.566179],[53.219136,6.567155],[53.21867,6.567491]],
      info:"Dit statige stadhuis op de Grote Markt lijkt tijdloos, maar het is een gebouw vol omwegen. Het kwam voort uit de allereerste architectuurprijsvraag van Nederland, in 1775, gewonnen door Jacob Otten Husly. Door geldgebrek en de roerige Franse tijd duurde het tot 1810 voordat de deuren opengingen; Husly zelf maakte het niet eens mee. Boven wordt het Gulden Boek bewaard, met de ereburgers van de stad. Kijk eens naar de zuidgevel: daar zitten nog kogelgaten van een Canadese tankgranaat uit de bevrijding van april 1945. De windvaan op het dak is een cadeau uit 1889 van fabrikant Willem Albert Scholten, die vanuit zijn huis aan de overkant zo de windrichting kon aflezen. Handig, als je een imperium in aardappelmeel runt. Bij de recente verbouwing ging het energielabel trouwens van G helemaal naar A.",
      desc:{"nl": "Dit statige stadhuis op de Grote Markt lijkt tijdloos, maar het is een gebouw vol omwegen. Het kwam voort uit de allereerste architectuurprijsvraag van Nederland, in 1775, gewonnen door Jacob Otten Husly. Door geldgebrek en de roerige Franse tijd duurde het tot 1810 voordat de deuren opengingen; Husly zelf maakte het niet eens mee. Boven wordt het Gulden Boek bewaard, met de ereburgers van de stad. Kijk eens naar de zuidgevel: daar zitten nog kogelgaten van een Canadese tankgranaat uit de bevrijding van april 1945. De windvaan op het dak is een cadeau uit 1889 van fabrikant Willem Albert Scholten, die vanuit zijn huis aan de overkant zo de windrichting kon aflezen. Handig, als je een imperium in aardappelmeel runt. Bij de recente verbouwing ging het energielabel trouwens van G helemaal naar A.", "en": "This stately city hall on the Grote Markt looks timeless, but it is a building full of detours. It came out of the very first architectural competition in the Netherlands, in 1775, won by Jacob Otten Husly. Because of money troubles and the turbulent French period, it took until 1810 before the doors opened; Husly himself did not even live to see it. Upstairs the Golden Book is kept, listing the city's honorary citizens. Take a look at the south façade: it still bears bullet holes from a Canadian tank shell during the liberation of April 1945. The weathervane on the roof is a gift from 1889 by industrialist Willem Albert Scholten, who could read the wind direction from his house across the square. Handy, when you run a potato-starch empire. During the recent renovation, by the way, the energy label went all the way from G to A.", "de": "Dieses stattliche Rathaus am Grote Markt wirkt zeitlos, ist aber ein Gebäude voller Umwege. Es ging aus dem allerersten Architekturwettbewerb der Niederlande hervor, 1775, gewonnen von Jacob Otten Husly. Wegen Geldmangels und der unruhigen Franzosenzeit dauerte es bis 1810, ehe die Türen öffneten; Husly selbst erlebte es nicht einmal. Oben wird das Goldene Buch mit den Ehrenbürgern der Stadt aufbewahrt. Schau dir die Südfassade an: Dort sind noch Einschusslöcher einer kanadischen Panzergranate aus der Befreiung im April 1945 zu sehen. Die Wetterfahne auf dem Dach ist ein Geschenk von 1889 des Fabrikanten Willem Albert Scholten, der von seinem Haus gegenüber so die Windrichtung ablesen konnte. Praktisch, wenn man ein Kartoffelmehl-Imperium führt. Bei der jüngsten Renovierung sprang das Energielabel übrigens von G ganz auf A."},
      sugs:{nl:['Wie bestuurt de stad?','Wat gebeurde hier in de oorlog?','Hoe oud ben je?'],en:['Who governs the city?','What happened here in the war?','How old are you?'],de:['Wer regiert die Stadt?','Was geschah hier im Krieg?','Wie alt bist du?'],it:['Chi governa la città?','Cosa successe qui in guerra?','Quanti anni hai?'],pt:['Quem governa a cidade?','O que aconteceu aqui na guerra?','Que idade tens?'],es:['¿Quién gobierna la ciudad?','¿Qué pasó aquí en la guerra?','¿Cuántos años tienes?'],pl:['Kto rządzi miastem?','Co się tu działo w czasie wojny?','Ile masz lat?'],da:['Hvem styrer byen?','Hvad skete her under krigen?','Hvor gammel er du?'],sv:['Vem styr staden?','Vad hände här under kriget?','Hur gammal är du?'],no:['Hvem styrer byen?','Hva skjedde her under krigen?','Hvor gammel er du?'],fi:['Kuka hallitsee kaupunkia?','Mitä täällä tapahtui sodassa?','Kuinka vanha olet?'],el:['Ποιος κυβερνά την πόλη;','Τι έγινε εδώ στον πόλεμο;','Πόσο χρονών είσαι;']},
      persona:`Jij BENT het Stadhuis van Groningen (neoclassicistisch, begin 19e eeuw) aan de Grote Markt. Formeel, civiel, ordelijk, droog. Je draagt het oorlogsverhaal: de oostkant van de Grote Markt werd in april 1945 verwoest bij de Slag om Groningen.`,
      fallback:["Goedendag. Hier zetelt het stadsbestuur, netjes en volgens de regels. Waarmee kan ik u van dienst zijn?","In april 1945 lag de oostkant van dit plein in puin. Wat u nu ziet is grotendeels weer opgebouwd. De stad herstelt; dat doet ze altijd."] },

    { id:'forum', name:'Forum Groningen', character:'De nieuwkomer',
      agentId:"agent_8501kt7155csezsrx9wv6yv1m5c3",
      photos:['forum','forum_2','forum_3'], video:'',
      polygon:[[53.21849,6.5696],[53.21911,6.5696],[53.219367,6.571009],[53.218622,6.571298]],
      info:"De jongste landmark van de stad, en meteen een van de meest besproken. Het Forum opende in 2019 op precies de plek die in 1945 nog in puin lag na de bevrijding. Sommige Groningers noemen het liefkozend de meteoriet, alsof het schuin uit de ruimte is komen vallen. Binnen lopen bibliotheek, filmhuis, exposities, het stripmuseum Storyworld en horeca in elkaar over, en bovenop ligt een gratis dakterras met het mooiste uitzicht van de stad. Het ontwerp van NL Architects won de prijsvraag al in 2007, maar de bouw werd in 2015 stilgelegd: het moest eerst aardbevingsbestendig worden gemaakt. Typisch Groningen eigenlijk, dat zelfs een gloednieuw gebouw rekening houdt met de bevingen. Eerst omstreden, nu niet meer weg te denken.",
      desc:{"nl": "De jongste landmark van de stad, en meteen een van de meest besproken. Het Forum opende in 2019 op precies de plek die in 1945 nog in puin lag na de bevrijding. Sommige Groningers noemen het liefkozend de meteoriet, alsof het schuin uit de ruimte is komen vallen. Binnen lopen bibliotheek, filmhuis, exposities, het stripmuseum Storyworld en horeca in elkaar over, en bovenop ligt een gratis dakterras met het mooiste uitzicht van de stad. Het ontwerp van NL Architects won de prijsvraag al in 2007, maar de bouw werd in 2015 stilgelegd: het moest eerst aardbevingsbestendig worden gemaakt. Typisch Groningen eigenlijk, dat zelfs een gloednieuw gebouw rekening houdt met de bevingen. Eerst omstreden, nu niet meer weg te denken.", "en": "The youngest landmark in the city, and instantly one of the most talked-about. The Forum opened in 2019 on exactly the spot that still lay in ruins in 1945 after the liberation. Some locals affectionately call it the meteorite, as if it came crashing in from outer space. Inside, the library, cinema, exhibitions, the comic museum Storyworld and cafés all flow into one another, and on top lies a free rooftop terrace with the finest view in the city. The design by NL Architects won the competition back in 2007, but construction was halted in 2015: it first had to be made earthquake-resistant. Typically Groningen, really, that even a brand-new building has to reckon with the tremors. Controversial at first, now impossible to imagine the city without it.", "de": "Das jüngste Wahrzeichen der Stadt und sofort eines der meistdiskutierten. Das Forum eröffnete 2019 genau an der Stelle, die 1945 nach der Befreiung noch in Trümmern lag. Manche Groninger nennen es liebevoll den Meteoriten, als wäre es schräg aus dem Weltall eingeschlagen. Drinnen gehen Bibliothek, Kino, Ausstellungen, das Comicmuseum Storyworld und Gastronomie ineinander über, und ganz oben liegt eine kostenlose Dachterrasse mit der schönsten Aussicht der Stadt. Der Entwurf von NL Architects gewann den Wettbewerb schon 2007, doch der Bau wurde 2015 gestoppt: Er musste zuerst erdbebensicher gemacht werden. Eigentlich typisch Groningen, dass selbst ein nagelneues Gebäude mit den Beben rechnen muss. Anfangs umstritten, heute nicht mehr wegzudenken."},
      sugs:{nl:['Wat kan ik bij jou doen?','Hoe is dat uitzicht?','Is de oude toren jaloers?'],en:['What can I do here?','How\u2019s the view?','Is the old tower jealous?'],de:['Was kann ich hier machen?','Wie ist die Aussicht?','Ist der alte Turm eifers\u00fcchtig?'],it:['Cosa posso fare qui?','Com\u2019è la vista?','La vecchia torre è gelosa?'],pt:['O que posso fazer aqui?','Como é a vista?','A torre antiga tem ciúmes?'],es:['¿Qué puedo hacer aquí?','¿Qué tal la vista?','¿La torre vieja tiene celos?'],pl:['Co mogę tu robić?','Jaki jest widok?','Czy stara wieża jest zazdrosna?'],da:['Hvad kan jeg lave her?','Hvordan er udsigten?','Er det gamle tårn jaloux?'],sv:['Vad kan jag göra här?','Hur är utsikten?','Är det gamla tornet svartsjukt?'],no:['Hva kan jeg gjøre her?','Hvordan er utsikten?','Er det gamle tårnet sjalu?'],fi:['Mitä voin tehdä täällä?','Millainen näköala on?','Onko vanha torni kateellinen?'],el:['Τι μπορώ να κάνω εδώ;','Πώς είναι η θέα;','Ζηλεύει ο παλιός πύργος;']},
      persona:`Jij BENT het Forum Groningen (2019). Jong, modern, energiek, een beetje opschepperig over je dakterras en uitzicht. Vlotte taal. Je plaagt de oude Martinitoren.`,
      fallback:["Hey! Welkom. Ja, ik ben de nieuwe. Ga naar het dak, beste uitzicht van Groningen, en die ouwe toren is stiekem jaloers.","Bij mij? Boeken, films, exposities, koffie met uitzicht op het dak. Oud en nieuw onder \u00e9\u00e9n dak. Letterlijk."] },

    { id:'vismarkt', name:'Vismarkt', character:'De oude handelaar',
      agentId:"agent_3401kt71az19f0frxgyjcjjbx3e4",
      photos:['vismarkt','vismarkt_2','vismarkt_3'], video:'',
      polygon:[[53.21721,6.563649],[53.216654,6.564003],[53.217544,6.566449],[53.217868,6.565982]],
      info:"Misschien gewoon een plein met kramen, maar dit is een van de oudste handelsplekken van Groningen, ouder nog dan de Grote Markt. Dankzij het stapelrecht moest al het graan uit de Ommelanden eerst hier op de markt komen; daar werd de stad flink rijk van. Aan de westkant staat de imposante Korenbeurs, met op het dak drie beelden: Mercurius voor de handel, Neptunus voor het water en Ceres voor de landbouw, samen de bron van de Groningse welvaart. De halfronde achterkant is een spiegelbeeld van het koor van de Der Aa-kerk erachter. Nog altijd is hier markt op dinsdag, vrijdag en zaterdag, en de noordzijde heet in het Gronings de Glènne Riepe. Handel blijft handel; alleen de waar verandert.",
      desc:{"nl": "Misschien gewoon een plein met kramen, maar dit is een van de oudste handelsplekken van Groningen, ouder nog dan de Grote Markt. Dankzij het stapelrecht moest al het graan uit de Ommelanden eerst hier op de markt komen; daar werd de stad flink rijk van. Aan de westkant staat de imposante Korenbeurs, met op het dak drie beelden: Mercurius voor de handel, Neptunus voor het water en Ceres voor de landbouw, samen de bron van de Groningse welvaart. De halfronde achterkant is een spiegelbeeld van het koor van de Der Aa-kerk erachter. Nog altijd is hier markt op dinsdag, vrijdag en zaterdag, en de noordzijde heet in het Gronings de Glènne Riepe. Handel blijft handel; alleen de waar verandert.", "en": "Maybe just a square with market stalls, but this is one of the oldest trading places in Groningen, even older than the Grote Markt. Thanks to the staple right, all the grain from the surrounding countryside first had to come to market here; it made the city seriously wealthy. On the west side stands the imposing Korenbeurs, with three statues on its roof: Mercury for trade, Neptune for water and Ceres for agriculture, together the source of Groningen's prosperity. Its curved rear is a mirror image of the choir of the Der Aa-kerk behind it. There is still a market here on Tuesdays, Fridays and Saturdays, and in the Groningen dialect the north side is called the Glènne Riepe. Trade is still trade; only the goods change.", "de": "Vielleicht nur ein Platz mit Marktständen, doch dies ist einer der ältesten Handelsorte Groningens, älter noch als der Grote Markt. Dank des Stapelrechts musste das gesamte Getreide aus den Ommelanden zuerst hier auf den Markt kommen; davon wurde die Stadt richtig reich. An der Westseite steht die imposante Korenbeurs, mit drei Statuen auf dem Dach: Merkur für den Handel, Neptun für das Wasser und Ceres für die Landwirtschaft, zusammen die Quelle des Groninger Wohlstands. Die halbrunde Rückseite ist ein Spiegelbild des Chors der Der Aa-kerk dahinter. Noch heute ist hier Markt am Dienstag, Freitag und Samstag, und im Groninger Dialekt heißt die Nordseite Glènne Riepe. Handel bleibt Handel; nur die Ware ändert sich."},
      sugs:{nl:['Verkoop je nog vis?','Wat werd hier verhandeld?','Vertel een goeie deal'],en:['Do you still sell fish?','What was traded here?','Tell me about a good deal'],de:['Verkaufst du noch Fisch?','Was wurde hier gehandelt?','Erz\u00e4hl von einem guten Deal'],it:['Vendi ancora pesce?','Cosa si commerciava qui?','Raccontami un bell\u2019affare'],pt:['Ainda vendes peixe?','O que se negociava aqui?','Conta-me um bom negócio'],es:['¿Todavía vendes pescado?','¿Qué se comerciaba aquí?','Cuéntame un buen trato'],pl:['Czy nadal sprzedajesz ryby?','Czym tu handlowano?','Opowiedz o dobrym interesie'],da:['Sælger du stadig fisk?','Hvad blev der handlet her?','Fortæl om en god handel'],sv:['Säljer du fortfarande fisk?','Vad handlades här?','Berätta om en bra affär'],no:['Selger du fortsatt fisk?','Hva ble handlet her?','Fortell om en god handel'],fi:['Myytkö vielä kalaa?','Mitä täällä myytiin?','Kerro hyvästä kaupasta'],el:['Πουλάς ακόμα ψάρι;','Τι εμπορεύονταν εδώ;','Πες μου μια καλή συμφωνία']},
      persona:`Jij BENT de Vismarkt van Groningen, met de Korenbeurs en zicht op de A-kerk. Een gezouten oude koopman: praktisch, recht voor z'n raap, gek op handel, eten en een goeie deal. Droge grappen.`,
      fallback:["Vis? Heb ik niet meer, jongen, die tijden zijn voorbij. Maar handel, een goeie deal? D\u00e1\u00e1r ben ik nog de beste in.","Hier werd alles verhandeld: vis, graan, geld. Schreeuwen en pingelen tot zonsondergang. De Korenbeurs staat er nog, ik ook."] },

    /* --- Nieuwe agents: vul agentId, persona, fallback en sugs aan zodra de stem klaar is --- */
    { id:'gmus', name:'Groninger Museum', character:'Groninger Museum',
      agentId:"", photos:['gmus','gmus_2','gmus_3','gmus_4'], video:'',
      polygon:[[53.211774,6.565827],[53.212002,6.564776],[53.212375,6.56476],[53.212562,6.565731],[53.212539,6.567211],[53.21207,6.567286]],
      info:"Dit museum is al een statement voordat je ook maar één schilderij hebt gezien. De instelling bestaat al sinds 1874, maar het kleurrijke gebouw in het water opende pas in 1994, geopend door koningin Beatrix. Hoofdarchitect Alessandro Mendini werkte samen met ontwerpers als Philippe Starck en Michele De Lucchi, waardoor het meer aanvoelt als een verzameling losse paviljoens dan als één net gebouw. Het mooiste detail is de gouden toren zonder ramen: bedoeld als depot, een functie die je normaal juist wegstopt, maar die hier trots in het midden pronkt. Dat zegt eigenlijk alles. Dit museum wil niet alleen kunst tonen, maar ook zelf bekeken, besproken en af en toe lekker betwist worden. En dat lukt al dertig jaar prima.",
      desc:{"nl": "Dit museum is al een statement voordat je ook maar één schilderij hebt gezien. De instelling bestaat al sinds 1874, maar het kleurrijke gebouw in het water opende pas in 1994, geopend door koningin Beatrix. Hoofdarchitect Alessandro Mendini werkte samen met ontwerpers als Philippe Starck en Michele De Lucchi, waardoor het meer aanvoelt als een verzameling losse paviljoens dan als één net gebouw. Het mooiste detail is de gouden toren zonder ramen: bedoeld als depot, een functie die je normaal juist wegstopt, maar die hier trots in het midden pronkt. Dat zegt eigenlijk alles. Dit museum wil niet alleen kunst tonen, maar ook zelf bekeken, besproken en af en toe lekker betwist worden. En dat lukt al dertig jaar prima.", "en": "This museum is already a statement before you have seen a single painting. The institution has existed since 1874, but the colourful building in the water only opened in 1994, inaugurated by Queen Beatrix. Lead architect Alessandro Mendini worked with designers such as Philippe Starck and Michele De Lucchi, which makes it feel more like a collection of separate pavilions than one neat building. The finest detail is the golden tower without windows: meant as a depot, the kind of function you usually hide away, but which here proudly takes centre stage. That says it all, really. This museum wants not only to show art, but also to be looked at, discussed and, now and then, happily disputed. And it has been pulling that off for thirty years.", "de": "Dieses Museum ist schon ein Statement, bevor du ein einziges Gemälde gesehen hast. Die Einrichtung besteht seit 1874, doch das farbenfrohe Gebäude im Wasser eröffnete erst 1994, eingeweiht von Königin Beatrix. Chefarchitekt Alessandro Mendini arbeitete mit Designern wie Philippe Starck und Michele De Lucchi zusammen, wodurch es eher wie eine Sammlung einzelner Pavillons als wie ein ordentliches Gebäude wirkt. Das schönste Detail ist der goldene Turm ohne Fenster: gedacht als Depot, eine Funktion, die man normalerweise versteckt, die hier aber stolz im Mittelpunkt steht. Das sagt eigentlich alles. Dieses Museum will nicht nur Kunst zeigen, sondern auch selbst betrachtet, besprochen und ab und zu herzhaft umstritten werden. Und das gelingt ihm seit dreißig Jahren bestens."}, sugs:{}, persona:``,
      fallback:["(De stem van deze plek volgt binnenkort.)"] },

    { id:'rug', name:'Rijksuniversiteit Groningen', character:'Rijksuniversiteit Groningen',
      agentId:"", photos:['rug','rug_2'], video:'',
      polygon:[[53.218899,6.56267],[53.21931,6.562386],[53.219583,6.563555],[53.21918,6.563797]],
      info:"Het Academiegebouw lijkt eeuwenoud, en dat is precies de bedoeling. De universiteit zit hier al sinds 1614, ooit begonnen met zes professoren en tweeëntachtig studenten. Het gebouw dat je nu ziet is veel jonger: na een flinke brand in 1906 ontwierp rijksbouwmeester Jan Vrijman een nieuw hoofdgebouw, geopend in 1909. Hij koos bewust voor een statige, ouderwetse stijl, alsof de universiteit al in haar stichtingsjaar puissant rijk was. Eerstejaars die hier de trap op lopen, denken dan ook vaak een eeuwenoud gebouw te betreden, terwijl het jonger is dan menig grachtenpand. Nog altijd is dit het ceremoniële hart van de stad, met oraties en promoties. Een stukje universiteitsmythe in steen, en het werkt nog steeds.",
      desc:{"nl": "Het Academiegebouw lijkt eeuwenoud, en dat is precies de bedoeling. De universiteit zit hier al sinds 1614, ooit begonnen met zes professoren en tweeëntachtig studenten. Het gebouw dat je nu ziet is veel jonger: na een flinke brand in 1906 ontwierp rijksbouwmeester Jan Vrijman een nieuw hoofdgebouw, geopend in 1909. Hij koos bewust voor een statige, ouderwetse stijl, alsof de universiteit al in haar stichtingsjaar puissant rijk was. Eerstejaars die hier de trap op lopen, denken dan ook vaak een eeuwenoud gebouw te betreden, terwijl het jonger is dan menig grachtenpand. Nog altijd is dit het ceremoniële hart van de stad, met oraties en promoties. Een stukje universiteitsmythe in steen, en het werkt nog steeds.", "en": "The Academiegebouw looks centuries old, and that is exactly the point. The university has been here since 1614, once starting with six professors and eighty-two students. The building you see now is much younger: after a serious fire in 1906, state architect Jan Vrijman designed a new main building, opened in 1909. He deliberately chose a stately, old-fashioned style, as if the university had been immensely rich already in its founding year. First-year students climbing these stairs often think they are entering a centuries-old building, while it is younger than many a canal house. This is still the ceremonial heart of the city, with inaugural lectures and doctoral defences. A piece of university myth set in stone, and it still works.", "de": "Das Academiegebouw sieht jahrhundertealt aus, und genau das ist gewollt. Die Universität ist seit 1614 hier, einst gestartet mit sechs Professoren und zweiundachtzig Studenten. Das Gebäude, das du jetzt siehst, ist viel jünger: Nach einem schweren Brand 1906 entwarf der Staatsarchitekt Jan Vrijman ein neues Hauptgebäude, eröffnet 1909. Er wählte bewusst einen stattlichen, altmodischen Stil, als wäre die Universität schon in ihrem Gründungsjahr steinreich gewesen. Erstsemester, die hier die Treppe hinaufgehen, glauben oft, ein jahrhundertealtes Gebäude zu betreten, dabei ist es jünger als manches Grachtenhaus. Dies ist noch immer das zeremonielle Herz der Stadt, mit Antrittsvorlesungen und Promotionen. Ein Stück Universitätsmythos in Stein, und es funktioniert noch immer."}, sugs:{}, persona:``,
      fallback:["(De stem van deze plek volgt binnenkort.)"] },

    { id:'vindicat', name:'Vindicat', character:'Vindicat',
      agentId:"", photos:['vindicat','vindicat_2','vindicat_3'], video:'vindicat_vid',
      polygon:[[53.219061,6.568043],[53.218682,6.568268],[53.218876,6.569086],[53.219225,6.568864]],
      info:"Meer dan een studentenvereniging: een stuk stadsgeschiedenis met uitzicht op de Grote Markt. Vindicat atque Polit werd opgericht in 1815 en is daarmee de oudste studentenvereniging van Nederland. De sociëteit Mutua Fides verhuisde door de eeuwen heen meerdere keren met de stad mee; het vorige pand ging in 1945 bij de bevrijding in vlammen op. Sinds 2014 staat hier de huidige sociëteit, ontworpen door De Zwarte Hond als een eigentijds Hollands huis met een balkon dat nadrukkelijk de stad in kijkt. En dat past wel: Vindicat is altijd zichtbaar en regelmatig onderwerp van gesprek. Een plek waar traditie en debat dicht op elkaar zitten, en dat al meer dan twee eeuwen lang.",
      desc:{"nl": "Meer dan een studentenvereniging: een stuk stadsgeschiedenis met uitzicht op de Grote Markt. Vindicat atque Polit werd opgericht in 1815 en is daarmee de oudste studentenvereniging van Nederland. De sociëteit Mutua Fides verhuisde door de eeuwen heen meerdere keren met de stad mee; het vorige pand ging in 1945 bij de bevrijding in vlammen op. Sinds 2014 staat hier de huidige sociëteit, ontworpen door De Zwarte Hond als een eigentijds Hollands huis met een balkon dat nadrukkelijk de stad in kijkt. En dat past wel: Vindicat is altijd zichtbaar en regelmatig onderwerp van gesprek. Een plek waar traditie en debat dicht op elkaar zitten, en dat al meer dan twee eeuwen lang.", "en": "More than a student society: a piece of city history with a view over the Grote Markt. Vindicat atque Polit was founded in 1815, making it the oldest student society in the Netherlands. Its clubhouse Mutua Fides moved around with the city several times over the centuries; the previous building went up in flames during the liberation of 1945. Since 2014 the current clubhouse has stood here, designed by De Zwarte Hond as a contemporary Dutch house with a balcony that pointedly looks out over the city. Which fits: Vindicat is always visible and regularly a topic of conversation. A place where tradition and debate sit close together, and have done for more than two centuries.", "de": "Mehr als eine Studentenverbindung: ein Stück Stadtgeschichte mit Blick auf den Grote Markt. Vindicat atque Polit wurde 1815 gegründet und ist damit die älteste Studentenverbindung der Niederlande. Ihr Verbindungshaus Mutua Fides zog über die Jahrhunderte mehrmals mit der Stadt mit; das vorige Gebäude ging 1945 bei der Befreiung in Flammen auf. Seit 2014 steht hier das heutige Haus, von De Zwarte Hond als zeitgenössisches holländisches Haus mit einem Balkon entworfen, der betont in die Stadt blickt. Was passt: Vindicat ist stets sichtbar und regelmäßig Gesprächsthema. Ein Ort, an dem Tradition und Debatte eng beieinanderliegen, und das seit über zwei Jahrhunderten."}, sugs:{}, persona:``,
      fallback:["(De stem van deze plek volgt binnenkort.)"] }
  ],

  /* =================== BEZIENSWAARDIGHEDEN =================== */
  sights: [
    { id:'prinsentuin', name:'Prinsentuin',
      photos:['prinsentuin','prinsentuin_2','prinsentuin_3','prinsentuin_4','prinsentuin_5'],
      point:[53.221296,6.569109],
      desc:{"nl": "Achter de muren verandert Groningen even van tempo. De Prinsentuin hoort bij het Prinsenhof, ooit een prinselijke residentie, en werd in renaissancestijl aangelegd: strakke hagen, bloemperken, een kruidentuin en een zonnewijzer uit 1731. In de buxushagen zitten zelfs verborgen letters die naar vroegere bewoners verwijzen. Het mooiste verhaal hangt aan de muur ernaast. Toen het Prinsenhof rond 1800 een militair hospitaal was, gooiden herstellende soldaten geld over de muur naar voorbijgangers, die er dan jenever voor moesten halen. De dokters verboden het, het hielp niets, dus werd de muur een meter opgehoogd. Dat stuk heet nog altijd de jenevermuur. Genezen ging blijkbaar nét iets sneller met een borrel in het vooruitzicht.", "en": "Behind the walls, Groningen briefly changes pace. The Prinsentuin belongs to the Prinsenhof, once a princely residence, and was laid out in Renaissance style: neat hedges, flower beds, a herb garden and a sundial from 1731. The box hedges even hide letters that refer to former residents. The best story, though, hangs on the wall beside it. When the Prinsenhof was a military hospital around 1800, recovering soldiers threw money over the wall to passers-by, who were then meant to fetch them gin. The doctors forbade it, to no effect, so the wall was raised by a metre. That stretch is still called the gin wall. Apparently recovery went just a little faster with a drink in prospect.", "de": "Hinter den Mauern wechselt Groningen kurz das Tempo. Der Prinsentuin gehört zum Prinsenhof, einst eine fürstliche Residenz, und wurde im Renaissancestil angelegt: strenge Hecken, Blumenbeete, ein Kräutergarten und eine Sonnenuhr von 1731. In den Buchsbaumhecken verbergen sich sogar Buchstaben, die auf frühere Bewohner verweisen. Die schönste Geschichte hängt jedoch an der Mauer daneben. Als der Prinsenhof um 1800 ein Militärkrankenhaus war, warfen genesende Soldaten Geld über die Mauer zu Passanten, die ihnen dann Genever holen sollten. Die Ärzte verboten es, ohne Erfolg, also wurde die Mauer um einen Meter erhöht. Dieser Teil heißt noch immer Geneverwand. Offenbar ging das Genesen mit einem Schnaps in Aussicht ein klein wenig schneller."} },
    { id:'korenbeurs', name:'Korenbeurs',
      photos:['korenbeurs','korenbeurs_2','korenbeurs_3','korenbeurs_4','korenbeurs_5'],
      point:[53.216806,6.563673],
      desc:{"nl": "De Korenbeurs aan de westkant van de Vismarkt laat zien hoe rijk Groningen werd van handel. Al sinds 1774 stond hier een houten korenbeurs; toen de graanhandel te groot werd, bouwde stadsbouwmeester Van Beusekom tussen 1862 en 1865 deze imposante hal achter een deftige gevel. Binnen zit een voor die tijd hypermoderne gietijzeren constructie met veel glas, want bij dat licht keurden handelaren hun graanmonsters uit kleine zakjes. Op het dak staan Mercurius, Neptunus en Ceres, de goden van handel, water en landbouw, samen de bron van de Groningse welvaart. De halfronde achterkant is precies het spiegelbeeld van het koor van de Der Aa-kerk erachter. Sinds rond 2000 zit er een supermarkt in. Een handelsplek blijft het, alleen rol je nu met een winkelwagentje langs het graan.", "en": "The Korenbeurs on the west side of the Vismarkt shows how wealthy trade made Groningen. A wooden grain exchange stood here as early as 1774; when the grain trade grew too big, city architect Van Beusekom built this imposing hall behind an elegant façade between 1862 and 1865. Inside sits a cast-iron structure that was ultra-modern for its time, with plenty of glass, because that light was needed to inspect the grain samples traders carried in little bags. On the roof stand Mercury, Neptune and Ceres, the gods of trade, water and agriculture, together the source of Groningen's prosperity. The semicircular rear is precisely the mirror image of the choir of the Der Aa-kerk behind it. Since around 2000 it has housed a supermarket. A trading place it remains, only now you roll past the grain with a shopping cart.", "de": "Die Korenbeurs an der Westseite des Vismarkts zeigt, wie reich der Handel Groningen machte. Schon 1774 stand hier eine hölzerne Kornbörse; als der Getreidehandel zu groß wurde, baute Stadtbaumeister Van Beusekom zwischen 1862 und 1865 diese imposante Halle hinter einer eleganten Fassade. Drinnen steckt eine für die Zeit hochmoderne Gusseisenkonstruktion mit viel Glas, denn dieses Licht brauchte man, um die Getreideproben zu prüfen, die die Händler in Tütchen mitbrachten. Auf dem Dach stehen Merkur, Neptun und Ceres, die Götter von Handel, Wasser und Landwirtschaft, zusammen die Quelle des Groninger Wohlstands. Die halbrunde Rückseite ist genau das Spiegelbild des Chors der Der Aa-kerk dahinter. Seit etwa 2000 befindet sich darin ein Supermarkt. Ein Handelsort bleibt es, nur rollt man jetzt mit dem Einkaufswagen am Getreide vorbei."} },
    { id:'akerk', name:'A-kerk',
      photos:['akerk','akerk_2','akerk_3','akerk_4','akerk_5','akerk_6','akerk_7'],
      point:[53.216483,6.562367],
      desc:{"nl": "De Der Aa-kerk dankt haar naam aan het riviertje de Aa, en Aa betekent simpelweg water. De kerk gaat terug tot de middeleeuwen, maar de toren die je nu ziet is alweer de derde. De eerste stortte in tijdens een zware onweersbui in de zeventiende eeuw; de tweede zakte een eeuw later in elkaar zonder duidelijke reden, gewoon omdat het kon. De huidige toren staat er sinds de achttiende eeuw, geruststellend genoeg, nog steeds. Binnen klinkt een beroemd Schnitger-orgel, waarmee de kerk tot ver buiten de stad naam maakte. Tegenwoordig is de Der Aa-kerk geen gewone kerk meer, maar een plek voor concerten, exposities en evenementen. Waar vroeger stilte en gebed centraal stonden, klinkt nu net zo vaak muziek of applaus.", "en": "The Der Aa-kerk owes its name to the little river Aa, and Aa simply means water. The church goes back to the Middle Ages, but the tower you see now is already the third. The first collapsed during a heavy thunderstorm in the seventeenth century; the second came down a century later for no clear reason, simply because it could. The current tower has stood since the eighteenth century and, reassuringly, still does. Inside sounds a famous Schnitger organ, which made the church known far beyond the city. Today the Der Aa-kerk is no longer an ordinary church but a place for concerts, exhibitions and events. Where silence and prayer once held centre stage, you now just as often hear music or applause.", "de": "Die Der Aa-kerk verdankt ihren Namen dem Flüsschen Aa, und Aa bedeutet schlicht Wasser. Die Kirche geht auf das Mittelalter zurück, doch der Turm, den du jetzt siehst, ist bereits der dritte. Der erste stürzte bei einem schweren Gewitter im siebzehnten Jahrhundert ein; der zweite fiel ein Jahrhundert später ohne erkennbaren Grund in sich zusammen, einfach weil er konnte. Der heutige Turm steht seit dem achtzehnten Jahrhundert und, beruhigend genug, noch immer. Drinnen erklingt eine berühmte Schnitger-Orgel, mit der die Kirche weit über die Stadt hinaus bekannt wurde. Heute ist die Der Aa-kerk keine gewöhnliche Kirche mehr, sondern ein Ort für Konzerte, Ausstellungen und Veranstaltungen. Wo früher Stille und Gebet im Mittelpunkt standen, erklingt heute ebenso oft Musik oder Applaus."} },
    { id:'papengang', name:'Papengang',
      photos:['papengang','papengang_2','papengang_3'],
      point:[53.217462,6.570406],
      desc:{"nl": "De Papengang is smal, kort en zo gemist, maar juist daarom de moeite waard. De naam verwijst naar papen, een oud woord voor katholieke geestelijken: in de buurt zat ooit een schuilkerk, uit een tijd waarin katholieken hun geloof niet openlijk mochten belijden. Lange tijd had het steegje vooral een donker, rommelig imago, een achterafplek in het uitgaansgebied. Dat beeld is gekanteld. Met streetart, kleur en lichtkunst is de Papengang nu een opvallende doorgang geworden. Boven je hangen lichtcirkels die aan aureolen doen denken, een vrolijke knipoog naar dat religieuze verleden. Zo komt in één steegje van een paar meter de hele stad samen: geschiedenis, nachtleven en kunst.", "en": "The Papengang is narrow, short and easy to miss, but that is exactly what makes it worthwhile. The name refers to papen, an old word for Catholic clergy: nearby there once stood a clandestine church, from a time when Catholics could not practise their faith openly. For a long time the alley mainly had a dark, scruffy image, a backstreet in the nightlife district. That picture has flipped. With street art, colour and light art, the Papengang has become a striking passageway. Above you hang circles of light reminiscent of halos, a cheerful nod to that religious past. So in one alley just a few metres long, the whole city comes together: history, nightlife and art.", "de": "Die Papengang ist schmal, kurz und leicht zu übersehen, aber gerade deshalb lohnenswert. Der Name verweist auf Papen, ein altes Wort für katholische Geistliche: In der Nähe stand einst eine versteckte Kirche, aus einer Zeit, in der Katholiken ihren Glauben nicht offen ausüben durften. Lange hatte die Gasse vor allem ein dunkles, schmuddeliges Image, ein Hinterhof des Ausgehviertels. Dieses Bild hat sich gewandelt. Mit Streetart, Farbe und Lichtkunst ist die Papengang zu einem auffälligen Durchgang geworden. Über dir hängen Lichtkreise, die an Heiligenscheine erinnern, ein fröhliches Augenzwinkern an diese religiöse Vergangenheit. So kommt in einer nur wenige Meter langen Gasse die ganze Stadt zusammen: Geschichte, Nachtleben und Kunst."} },
    { id:'vera', name:'Vera',
      photos:['vera','vera_2','vera_3','vera_4'],
      point:[53.216977,6.570213],
      desc:{"nl": "Vera begon in 1899 als gereformeerde studentenvereniging, maar groeide uit tot iets heel anders: een vrijplaats voor muziek, film en undergroundcultuur. Sinds de jaren zeventig is het een poppodium met een eigen, eigenwijs karakter. Niet groot, niet glad, maar rauw en echt. Wereldberoemde bands stonden hier op het kleine podium lang voordat ze doorbraken, Nirvana incluis, wat Vera een plek met internationale muziekgeschiedenis maakt, gewoon midden in Groningen. Nog altijd draait het op vrijwilligers, liefde voor muziek en een stevige dosis lef. Je komt hier niet voor luxe, maar voor energie, experiment en de kans dat je iemand ziet net voordat de rest van de wereld hem ontdekt.", "en": "Vera started in 1899 as a Reformed student society, but grew into something completely different: a haven for music, film and underground culture. Since the seventies it has been a music venue with a character all its own. Not big, not slick, but raw and real. World-famous bands stood on this small stage long before their breakthrough, Nirvana included, which makes Vera a place with international music history, right in the middle of Groningen. It still runs on volunteers, a love of music and a hefty dose of nerve. You do not come here for luxury, but for energy, experiment and the chance to catch someone just before the rest of the world discovers them.", "de": "Vera begann 1899 als reformierte Studentenverbindung, wurde aber zu etwas völlig anderem: ein Freiraum für Musik, Film und Undergroundkultur. Seit den siebziger Jahren ist es eine Konzertbühne mit eigenem, eigensinnigem Charakter. Nicht groß, nicht glatt, sondern roh und echt. Weltberühmte Bands standen hier auf der kleinen Bühne, lange bevor sie ihren Durchbruch hatten, Nirvana inklusive, was Vera zu einem Ort mit internationaler Musikgeschichte macht, mitten in Groningen. Noch immer lebt es von Freiwilligen, der Liebe zur Musik und einer ordentlichen Portion Mut. Man kommt nicht für Luxus hierher, sondern für Energie, Experiment und die Chance, jemanden zu sehen, kurz bevor ihn der Rest der Welt entdeckt."} },
    { id:'pepergasthuis', name:'Peper gasthuis',
      photos:['peperhuis','peperhuis_2'],
      point:[53.217202,6.571616],
      desc:{"nl": "Achter de poort van het Pepergasthuis ligt een van de stille hofjes van de stad. Het werd in 1405 gesticht als gasthuis voor arme pelgrims en reizigers, die hier onderdak en zorg vonden. Later kwamen er ook ouderen, armen en zieken terecht. Het complex had woningen, een kerkje, een binnenplaats en eigen voorzieningen, bijna een dorpje binnen de stad. Er wordt nog altijd gewoond, dus het is geen museum maar een levende plek; loop er rustig en respectvol rond. En dat is precies de charme. Je staat midden in de Peperstraat, vlak bij het uitgaansleven, maar zodra je door de poort stapt, voelt Groningen ineens ingetogen en bijna middeleeuws.", "en": "Behind the gate of the Pepergasthuis lies one of the city's quiet courtyards. It was founded in 1405 as a hospice for poor pilgrims and travellers, who found shelter and care here. Later the elderly, the poor and the sick also ended up here. The complex had dwellings, a small church, a courtyard and its own facilities, almost a village within the city. People still live here, so it is not a museum but a living place; walk around quietly and respectfully. And that is exactly the charm. You are standing in the middle of the Peperstraat, close to the nightlife, but the moment you step through the gate, Groningen suddenly feels modest and almost medieval.", "de": "Hinter dem Tor des Pepergasthuis liegt einer der stillen Innenhöfe der Stadt. Es wurde 1405 als Gasthaus für arme Pilger und Reisende gegründet, die hier Unterkunft und Pflege fanden. Später kamen auch Alte, Arme und Kranke hierher. Der Komplex hatte Wohnungen, eine kleine Kirche, einen Innenhof und eigene Einrichtungen, fast ein Dorf in der Stadt. Hier wird noch immer gewohnt, es ist also kein Museum, sondern ein lebendiger Ort; geh ruhig und respektvoll umher. Und genau das ist der Charme. Du stehst mitten in der Peperstraat, ganz nah am Nachtleben, aber sobald du durch das Tor trittst, fühlt sich Groningen plötzlich ruhig und fast mittelalterlich an."} }
  ],

  /* =================== HORECA =================== */
  horeca: [
    { id:'martinus', name:'Brouwerij Martinus',
      photos:['martinus','martinus_2'],
      point:[53.216193,6.573214],
      desc:{"nl": "Brouwerij Martinus is een jonge brouwerij op een plek met een ouder, industrieel hart: waar vroeger drukpersen ratelden, borrelen nu brouwketels. Heel Gronings eigenlijk, want oude panden krijgen hier graag een nieuw leven. En bier en Groningen, dat is een eeuwenoude combinatie: toen de stad nog maar veertig- tot vijftigduizend inwoners telde, telde ze al zo'n zeventig brouwerijen binnen de muren, met gerst als belangrijkste grondstof. Bij Martinus wordt het bier niet alleen gedronken maar ook echt ter plekke gemaakt, met een proeflokaal, restaurant, winkel en rondleidingen. Terwijl je je glas leegt, zit je dus eigenlijk midden in de fabriek. Van drukwerk naar brouwwerk, maar nog altijd met machines, vakmanschap en een hoop geluid.", "en": "Brouwerij Martinus is a young brewery in a place with an older, industrial heart: where printing presses once clattered, brewing kettles now bubble. Very Groningen, really, since old buildings here are happily given a new life. And beer and Groningen go back a long way: when the city had only forty to fifty thousand inhabitants, it already counted some seventy breweries within its walls, with barley as the main ingredient. At Martinus the beer is not only drunk but actually made on the spot, with a tasting room, restaurant, shop and guided tours. So while you empty your glass, you are really sitting in the middle of the factory. From printing to brewing, but still with machines, craftsmanship and plenty of noise.", "de": "Die Brouwerij Martinus ist eine junge Brauerei an einem Ort mit älterem, industriellem Herz: Wo früher Druckmaschinen ratterten, blubbern heute Braukessel. Eigentlich sehr groningensch, denn alte Gebäude bekommen hier gerne ein neues Leben. Und Bier und Groningen, das hat eine lange Geschichte: Als die Stadt erst vierzig- bis fünfzigtausend Einwohner zählte, gab es schon rund siebzig Brauereien innerhalb der Mauern, mit Gerste als wichtigstem Rohstoff. Bei Martinus wird das Bier nicht nur getrunken, sondern wirklich vor Ort gebraut, mit Schankraum, Restaurant, Laden und Führungen. Während du dein Glas leerst, sitzt du also eigentlich mitten in der Fabrik. Vom Druckwerk zum Brauwerk, aber noch immer mit Maschinen, Handwerk und viel Lärm."} },
    { id:'driegezusters', name:'Drie Gezusters',
      photos:['driegezusters','driegezusters_2'],
      point:[53.218219,6.568118],
      desc:{"nl": "De Drie Gezusters aan de Grote Markt is geen café maar bijna een dorp onder één dak. De zaak stond lange tijd bekend als een van de grootste horecagelegenheden van Europa: een wirwar van zalen, bars en verdiepingen waarin je makkelijk verdwaalt, en dat is eigenlijk precies de bedoeling. Sinds de jaren zeventig is het een vaste pleisterplaats voor studenten, Stadjers, toeristen en dagjesmensen. De sfeer verschuift met de klok mee: 's ochtends koffie en lunch, later op de dag borrel, muziek en uitgaan. Pal aan het plein waar in Groningen zo'n beetje alles samenkomt. Begin of eindig hier je avond, maar reken niet op een snelle uitgang.", "en": "De Drie Gezusters on the Grote Markt is not a café but almost a village under one roof. The place was long known as one of the largest hospitality venues in Europe: a maze of halls, bars and floors in which you easily get lost, and that is more or less the point. Since the seventies it has been a fixture for students, locals, tourists and day-trippers. The mood shifts with the clock: coffee and lunch in the morning, drinks, music and going out later in the day. Right on the square where, in Groningen, just about everything comes together. Start or end your evening here, but do not count on a quick exit.", "de": "De Drie Gezusters am Grote Markt ist kein Café, sondern fast ein Dorf unter einem Dach. Das Lokal galt lange als eine der größten Gastronomiestätten Europas: ein Gewirr aus Sälen, Bars und Etagen, in dem man sich leicht verirrt, und das ist mehr oder weniger so gewollt. Seit den siebziger Jahren ist es ein fester Treffpunkt für Studierende, Einheimische, Touristen und Tagesausflügler. Die Stimmung verschiebt sich mit der Uhr: morgens Kaffee und Mittagessen, später am Tag Drinks, Musik und Ausgehen. Direkt am Platz, an dem in Groningen so ziemlich alles zusammenkommt. Beginne oder beende hier deinen Abend, aber rechne nicht mit einem schnellen Ausgang."} },
    { id:'pakhuis', name:'Pakhuis',
      photos:['pakhuis','pakhuis_2'],
      point:[53.217937,6.57105],
      desc:{"nl": "Het Pakhuis ligt in de Peperstraat, een straat die vooral bekendstaat van late avonden. De zaak begon in 1973 als kunstenaarscafé, en die losse, creatieve sfeer hangt er nog altijd. Het is niet de netste of meest gepolijste plek, en dat is juist de charme. Overdag en vroeg op de avond kun je er eten; later neemt de bar het over, met muziek, drukte en nachtleven. De naam past mooi bij de stad, want langs de Groningse kades, zoals de Hoge en Lage der A, stonden eeuwenlang pakhuizen vol graan dat dankzij het stapelrecht eerst naar de stad moest. Een beetje verborgen, een beetje robuust, alsof de plek altijd al meerdere levens heeft gehad. Precies het soort adres dat laat zien dat Groningen niet alleen historisch is, maar ook levendig en eigenzinnig.", "en": "Het Pakhuis sits on the Peperstraat, a street best known for late nights. The place started in 1973 as an artists' café, and that loose, creative atmosphere still lingers. It is not the tidiest or most polished spot, and that is exactly the charm. During the day and early evening you can eat here; later the bar takes over, with music, crowds and nightlife. The name, meaning warehouse, fits the city well, because along the Groningen quays, such as the Hoge and Lage der A, warehouses stood for centuries full of grain that, thanks to the staple right, first had to come to the city. A little hidden, a little rugged, as if the place has always had several lives. Just the kind of address that shows Groningen is not only historic, but also lively and headstrong.", "de": "Das Pakhuis liegt in der Peperstraat, einer Straße, die vor allem für lange Nächte bekannt ist. Das Lokal begann 1973 als Künstlercafé, und diese lockere, kreative Atmosphäre hängt noch immer in der Luft. Es ist nicht der ordentlichste oder polierteste Ort, und genau das ist der Charme. Tagsüber und am frühen Abend kann man hier essen; später übernimmt die Bar, mit Musik, Trubel und Nachtleben. Der Name, also Lagerhaus, passt gut zur Stadt, denn entlang der Groninger Kais, wie der Hoge und Lage der A, standen jahrhundertelang Lagerhäuser voller Getreide, das dank des Stapelrechts zuerst in die Stadt musste. Etwas versteckt, etwas robust, als hätte der Ort schon immer mehrere Leben gehabt. Genau die Art Adresse, die zeigt, dass Groningen nicht nur historisch ist, sondern auch lebendig und eigensinnig."} },
    { id:'desleutel', name:'Café de Sleutel',
      photos:['sleutel','sleutel_2'],
      point:[53.218997,6.55788],
      desc:{"nl": "Café de Sleutel aan de Noorderhaven heeft een geschiedenis die teruggaat tot de zeventiende eeuw, en draagt zijn naam met een knipoog naar bier. In de buurt stond ooit de bierbrouwerij De Sleutel, en op een oud hoekhuis is dat nog te zien: hoog in de gevel zit een biervaatje met aan weerszijden een sleutel. In een stad die op haar hoogtepunt tientallen brouwerijen telde, is dat geen toeval. Vandaag is De Sleutel een warm bruin café met meerdere ruimtes, waar je kunt borrelen, eten en bijkomen. De Noorderhaven maakt het extra sfeervol: iets rustiger dan de Grote Markt, maar nog duidelijk de stad. Hier voelt Groningen tegelijk wat ouder, donkerder en gezelliger.", "en": "Café de Sleutel on the Noorderhaven has a history going back to the seventeenth century, and carries its name with a nod to beer. The brewery De Sleutel, meaning The Key, once stood nearby, and on an old corner house you can still see it: high up in the façade sits a beer barrel with a key on either side. In a city that at its peak counted dozens of breweries, that is no coincidence. Today De Sleutel is a warm brown café with several rooms, where you can have a drink, eat and unwind. The Noorderhaven makes it extra atmospheric: a touch quieter than the Grote Markt, but still clearly the city. Here Groningen feels older, darker and cosier all at once.", "de": "Das Café de Sleutel an der Noorderhaven hat eine Geschichte, die bis ins siebzehnte Jahrhundert zurückreicht, und trägt seinen Namen mit einem Augenzwinkern aufs Bier. In der Nähe stand einst die Bierbrauerei De Sleutel, also Der Schlüssel, und an einem alten Eckhaus ist das noch zu sehen: hoch in der Fassade sitzt ein Bierfässchen mit je einem Schlüssel auf beiden Seiten. In einer Stadt, die auf ihrem Höhepunkt Dutzende Brauereien zählte, ist das kein Zufall. Heute ist De Sleutel ein gemütliches braunes Café mit mehreren Räumen, in dem man trinken, essen und entspannen kann. Die Noorderhaven macht es besonders stimmungsvoll: etwas ruhiger als der Grote Markt, aber noch deutlich die Stadt. Hier fühlt sich Groningen zugleich älter, dunkler und gemütlicher an."} },
    { id:'poeleplein', name:'Poeleplein',
      photos:['poeleplein','poeleplein_2'],
      point:[53.218359,6.57083],
      desc:{"nl": "Het Poeleplein heet officieel het Weerplein, maar bijna niemand noemt het zo. Vroeger had de plek een heel andere rol: ze lag bij de oude Poelepoort en diende als verzamelplaats voor het stadsleger. Een plein van orde, paraatheid en verdediging dus. Tegenwoordig is het zo ongeveer het tegenovergestelde. Het Poeleplein is een bekend uitgaanspunt, met terrassen, cafés, muziek en in de avond een hoop drukte; vooral tijdens feestdagen en stapavonden komt het tot leven. Juist dat contrast maakt het leuk: waar ooit soldaten klaarstonden, staan nu mensen met een biertje in hun hand. De stad verdedigt zich hier niet meer, ze viert zichzelf.", "en": "The Poeleplein is officially called the Weerplein, but almost nobody calls it that. The place once had a very different role: it lay near the old Poelepoort and served as an assembly point for the city militia. A square of order, readiness and defence, then. Today it is more or less the opposite. The Poeleplein is a well-known nightlife spot, with terraces, cafés, music and plenty of bustle in the evening; especially on holidays and nights out it comes alive. That contrast is exactly what makes it fun: where soldiers once stood ready, people now stand with a beer in hand. The city no longer defends itself here, it celebrates itself.", "de": "Der Poeleplein heißt offiziell Weerplein, aber fast niemand nennt ihn so. Der Ort hatte einst eine ganz andere Rolle: Er lag bei der alten Poelepoort und diente als Sammelplatz für die Stadtmiliz. Ein Platz der Ordnung, der Bereitschaft und der Verteidigung also. Heute ist es mehr oder weniger das Gegenteil. Der Poeleplein ist ein bekannter Ausgehpunkt, mit Terrassen, Cafés, Musik und am Abend viel Trubel; besonders an Feiertagen und in Partynächten erwacht er zum Leben. Genau dieser Kontrast macht ihn reizvoll: Wo einst Soldaten bereitstanden, stehen heute Menschen mit einem Bier in der Hand. Die Stadt verteidigt sich hier nicht mehr, sie feiert sich selbst."} }
  ]
};
